### ISSUE TITLE
deal with Bintray disappearing

### ISSUE THREAD

**Issue by SethTisue** [lightbend/lightbend-emoji#114]
As far as I know, there's never been any real reason this library isn't published to Maven Central via Sonatype.

We could switch to that, using sbt-ci-release. So basically go the generic OSS route rather than staying Lightbend-specific. That's what I'm in the process of doing over at https://github.com/lightbend/scala-logging/issues/254.

Another possibility is to wait and see what the Lightbend IT and Lightbend OSS folks decide to do with repo.typesafe.com / repo.lightbend.com, and then stay there.

For the time being, I think it's fine to do nothing and just wait and see what develops.

**Comment by SethTisue** [comment]
I will go ahead with the Sonatype option, sometime soon-isn

**Comment by SethTisue** [comment]
version 1.2.2 is on Maven Central

**Comment by SethTisue** [comment]
fwiw, I'm seeing previously published versions at https://cloudsmith.io/~lightbend/repos/ivy-releases/packages/ , so that seems like a good sign that they'll remain available once our internal Bintray -> Cloudsmith is complete (they are getting near done)

**Comment by Philippus** [comment]
Everybody was really sad the 12th of April, but unable to express it. 😢
