### ISSUE TITLE
roll a new release with Emojilator

### ISSUE THREAD

**Issue by SethTisue** [lightbend/lightbend-emoji#18]
@som-snytt having, under duress, added it to the readme (#14), now we have to do a release, too!

**Comment by SethTisue** [comment]
https://github.com/lightbend/lightbend-emoji/releases/tag/1.2.0

8e44ddf489823a4b3b447b30a068af5d1b9f77e7 documents the release steps

**Comment by SethTisue** [comment]
more JARs added to humanity's permanent cultural heritage

**Comment by SethTisue** [comment]
@som-snytt 

[info] - **should not go** kaput on bad short name
[info] - should **gently** ignore bad characters

😡, 😡 against the ☠️ of the ✨

**Comment by som-snytt** [comment]
Am I in trouble? I don't actually use emoji, but I'm trying to work them into an internal app at the office.

**Comment by SethTisue** [comment]
@som-snytt you're not in trouble, but I'll be disappointed if your next round of test cases doesn't result in poetry when read zig-zag fashion

**Comment by som-snytt** [comment]
I must be slowing down. Good night!

**Comment by wsargent** [comment]
everything make sense now
