### ISSUE TITLE
Roll a release

### ISSUE THREAD

**Issue by SethTisue** [lightbend/lightbend-emoji#184]
The masses are clamoring for a release of @som-snytt's https://github.com/lightbend/lightbend-emoji/pull/177

Should we call it 1.3, or 2.0? What does MiMA think?

**Comment by SethTisue** [comment]
We have not released for Scala 3 yet, only for prereleases. I think calling it 1.3 seems fine.

**Comment by SethTisue** [comment]
* release: https://github.com/lightbend/lightbend-emoji/releases/tag/1.3.0
* publishing job: https://github.com/lightbend/lightbend-emoji/actions/runs/2757770848

**Comment by SethTisue** [comment]
let the floodgates of Scala 3 adoption now open! https://repo1.maven.org/maven2/com/lightbend/emoji_3/1.3.0/

**Comment by SethTisue** [comment]
followup: #185

**Comment by som-snytt** [comment]
I forgot to enable `-Wvalue-discard`.
