### ISSUE TITLE
Support e"\:" instead of double colon

### ISSUE THREAD

**Issue by wsargent** [lightbend/lightbend-emoji#19]
> I'll create an issue to support e"\:" instead of double colon; I was too lazy, and StringContext doesn't make it trivial. I considered catching InvalidEscapeException and fixing escaped colon that way. That would be embarrassing, but maybe less than e"::".

https://github.com/lightbend/lightbend-emoji/pull/14#issuecomment-348866640

**Comment by som-snytt** [comment]
Nothing more luxurious than standing at the head of the PR queue.
